spring:
  application:
    name: "product"
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product-service

management:
  endpoints:
    web:
      exposures:
        include: "*"
  info:
    env:
      enabled: true
endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "product"
    description: "Product Application Services"
    version: "1.0.0"
